### ISSUE TITLE
Alter Periodic Task schedule

### ISSUE THREAD

**Issue by andersdd** [ovh/celery-director#106]
Could it be possible to amend the periodic task schedule from within Director?  Say from 60 seconds to 120 seconds?  Obviously without having to restart celery and director.  Or is the only means to amend the workflow and restart?

**Comment by ncrocfer** [comment]
Not it's not possible, Celery Director uses the default `celery.beat:PersistentScheduler` provided by Celery (see https://docs.celeryproject.org/en/latest/userguide/configuration.html#beat-scheduler).

By default the schedules are given in the [beat_schedule](https://github.com/ovh/celery-director/blob/93775338ee725a16b955a2ac1f87b31f6f2d7517/director/__init__.py#L90) setting, loaded when Celery starts.

So indeed the only method to change your workflows schedule is to amend your workflow and restart Celery.
