### ISSUE TITLE
Outdated flask package version resulting in import error from itsdangerous (breaking package)

### ISSUE THREAD

**Issue by CodePint** [ovh/celery-director#125]
When trying to run our celery-director project we are getting this error:

```
cannot import name 'json' from 'itsdangerous' 
(/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

This was caused by a new release of `itsdangerous` and an unsupported version of Flask being used in `requirements.txt`
https://itsdangerous.palletsprojects.com/en/2.1.x/changes/
https://github.com/pallets/itsdangerous/issues/289
https://github.com/ovh/celery-director/blob/d2d0bfbffbf55b3e624a1393800044f9af7040ce/requirements.txt#L15

The best fix would appear to be updating requirements.txt to use `Flask~=2.0.0`
https://flask.palletsprojects.com/en/2.0.x/changes/

**Comment by CodePint** [comment]
These changes to requirements.txt fixed the issue
I can create a PR if you would like?  
Would you prefer hard pinned requirements or is this okay?

```
Flask~=2.0.0
Werkzeug~=2.0.0
```

**Comment by ncrocfer** [comment]
Sorry for the delay to answer, we prefer hard pinned requirements.
