### ISSUE TITLE
Move from Fask to FastAPI ?

### ISSUE THREAD

**Issue by PaulinCharliquart** [ovh/celery-director#139]
hi,

FastAPI is a nice tool to build API services with documentation. 

Some of advantages:
- build-in documentation
- easy configuration of Authentication
- async 

Are you interested by switching to FastAPI?

Thanks,
Paulin

**Comment by PaulinCharliquart** [comment]
no specific ones right now. Just wanted to hear your opinion on this.

**Comment by ncrocfer** [comment]
Ok :) So let's keep Flask, it works well ;)
