### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by PaulinCharliquart** [ovh/celery-director#140]
hi,

Here is some suggestions of UI improvement:

1. add the following env variables to update UI:

```
# should be stored in static folder
DIRECTOR_FAVICON="favicon.png"

DIRECTOR_NAV_COLOR="#3c4652"
DIRECTOR_REPO_LINK="https://github.com/ovh/celery-director" # or false to hide it

```

2.  Add filter by project name

I can submit a merge request if you agreed with these changes.

regards,
Paulin

**Comment by ncrocfer** [comment]
Hi @PaulinCharliquart,

Yes why not, PR is welcome :)

**Comment by ncrocfer** [comment]
PR is now merged in master, thanks for your contribution :)
