### ISSUE TITLE
request to upgrade psycopg2-binary dependency

### ISSUE THREAD

**Issue by madhuravius** [ovh/celery-director#142]
If this continues to use psycopg2-binary, i think there is a newer version out that is supported on m1 macs (https://github.com/psycopg/psycopg2/issues/1286) 

2.9.3 seems to work and pull fine for m1 now as resolved by an update to the library, but this one is still using 2.8.x which is causing issues

related issue possibly: https://github.com/ovh/celery-director/issues/129

if possible, would be nice, 🙇 

---

https://github.com/ovh/celery-director/pull/143 <-- contains this change but wasn't sure if my PR followed contributing guidelines. 

I can reopen or someone else can if desired, thanks

**Comment by ncrocfer** [comment]
I think it's a good idea to upgrade packages, you can open your PR and we'll test it :)

**Comment by madhuravius** [comment]
This should've been merged in and the issue has been addressed, thanks.
