### ISSUE TITLE
Not able to start director from the quickstart template

### ISSUE THREAD

**Issue by igoncharov85** [ovh/celery-director#165]
Hi,
I'm doing this on Windows, I have python 3.10 installed and was following https://ovh.github.io/celery-director/quickstart/.
I created an empty project in PyCharm, installed celery-director.

`director init workflows`
`set DIRECTOR_HOME=C:\folder\workflows`

`director db init`

> (venv) C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director>director db init
> 
> (venv) C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director>Usage: flask db init [OPTIONS]
> Try 'flask db init --help' for help.
> 
> Error: While importing 'director._auto', an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\flask\cli.py", line 234, in locate_app
>     __import__(module_name)
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\_auto.py", line 6, in <module>
>     app = create_app()
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\__init__.py", line 81, in create_app
>     cel_workflows.init_app(app)
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\extensions.py", line 32, in init_app
>     self.import_user_tasks()
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\extensions.py", line 65, in import_user_tasks
>     __import__(
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\pluginbase.py", line 438, in plugin_import
>     return self._system_import(import_name, globals, locals,
> ModuleNotFoundError: No module named 'pluginbase._internalspace._spd03ec0437c4fa3f853d6ce871fb3cfce.tasks\\etl'
> 

`director db upgrade`

> (venv) C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director>director db upgrade
> 
> (venv) C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director>Usage: flask db upgrade [OPTIONS] [REVISION]
> Try 'flask db upgrade --help' for help.
> 
> Error: While importing 'director._auto', an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\flask\cli.py", line 234, in locate_app
>     __import__(module_name)
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\_auto.py", line 6, in <module>
>     app = create_app()
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\__init__.py", line 81, in create_app
>     cel_workflows.init_app(app)
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\extensions.py", line 32, in init_app
>     self.import_user_tasks()
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\director\extensions.py", line 65, in import_user_tasks
>     __import__(
>   File "C:\Users\ihar\OneDrive\Desktop\GitHub\test-celery-director\venv\lib\site-packages\pluginbase.py", line 438, in plugin_import
>     return self._system_import(import_name, globals, locals,
> ModuleNotFoundError: No module named 'pluginbase._internalspace._sp335ccb1565a94e45e042bab25a06508e.tasks\\etl'

**Comment by ncrocfer** [comment]
Hi @igoncharov85 ,

I think the problem comes from Windows.

Even if Python 3.10 is not yet officially supported by Celery Director (see the [classifiers](https://github.com/ovh/celery-director/blob/master/setup.py#L47)), I tried it and it worked well:

```
$ python --version
Python 3.10.0
$ pip --version
pip 22.2.2 from /home/debian/venv/lib/python3.10/site-packages/pip (python 3.10)
$ pip install celery-director
[...]
Successfully installed Flask-2.1.1 Flask-HTTPAuth-4.5.0 Flask-Migrate-3.1.0 Flask-SQLAlchemy-2.5.1 Flask-json-schema-0.0.5 Jinja2-3.1.2 Mako-1.2.2 MarkupSafe-2.1.1 SQLAlchemy-1.3.11 Werkzeug-2.1.1 alembic-1.3.2 amqp-5.1.1 async-timeout-4.0.2 attrs-22.1.0 billiard-3.6.4.0 celery-5.2.6 celery-director-0.6.0 certifi-2022.6.15 click-8.1.3 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.2.0 deprecated-1.2.13 environs-6.1.0 flower-1.1.0 gunicorn-20.0.4 humanize-4.3.0 itsdangerous-2.1.2 jsonschema-4.15.0 kombu-5.2.4 marshmallow-3.17.1 mysql-connector-python-8.0.21 packaging-21.3 pluginbase-1.0.0 prometheus-client-0.14.1 prompt-toolkit-3.0.31 protobuf-4.21.5 psycopg2-binary-2.9.3 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 python-dotenv-0.21.0 python-editor-1.0.4 pytz-2022.2.1 pyyaml-5.4.1 redis-4.2.2 sentry-sdk-0.16.3 six-1.16.0 sqlalchemy-utils-0.35.0 terminaltables-3.1.0 tornado-6.2 urllib3-1.26.12 vine-5.0.0 wcwidth-0.2.5 wrapt-1.14.1
$ director --version
director, version 0.6.0
$ director init workflows
[*] Project created in /home/debian/workflows
[*] Do not forget to initialize the database
You can now export the DIRECTOR_HOME environment variable
$ export DIRECTOR_HOME=/home/debian/workflows
$ director db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 30d6f6636351, Initial migration
INFO  [alembic.runtime.migration] Running upgrade 30d6f6636351 -> 05cf96d6fcae, Add task result
INFO  [alembic.runtime.migration] Running upgrade 05cf96d6fcae -> 3f8466b16023, Add users table
INFO  [alembic.runtime.migration] Running upgrade 3f8466b16023 -> 063ff371f2da, Add index on workflow_id in task table
INFO  [alembic.runtime.migration] Running upgrade 063ff371f2da -> 2ac615d6850b, Force varchar 255
INFO  [alembic.runtime.migration] Running upgrade 2ac615d6850b -> 46e4acde004e, Add cascade in task model for workflow deletion
$ director webserver
[2022-09-08 13:16:20 +0000] [26301] [INFO] Starting gunicorn 20.0.4
[2022-09-08 13:16:20 +0000] [26301] [INFO] Listening at: http://127.0.0.1:8000 (26301)
[2022-09-08 13:16:20 +0000] [26301] [INFO] Using worker: sync
[2022-09-08 13:16:20 +0000] [26302] [INFO] Booting worker with pid: 2630
```

To be really honest I don't have a Windows to try Celery Director on it, and I'm not sure if someone already tested this OS with the tool ^^

I will search someone to confirm the problem comes from Windows, but I'm not sure we'll be able to quickly fix it...

**Comment by igoncharov85** [comment]
Originally I tried it on Python 3.7 and I think the issue comes from the Windows subsystem.

**Comment by ncrocfer** [comment]
If someone has Windows and can try to reproduce this issue that would be very nice 👍

**Comment by ncrocfer** [comment]
After checking the official documentation of Celery it seems Windows is no longer supported since Celery 4.x: https://docs.celeryq.dev/en/stable/faq.html#does-celery-support-windows

Celery Director being based on Celery, the same rule applies to it.

**Comment by dppss90008** [comment]
I encounter the same error, while my os platform is linux (CentOS Linux release 7.9.2009 (Core))

director db upgrade

Usage: flask db upgrade [OPTIONS] [REVISION]
Try 'flask db upgrade --help' for help.

Error: While importing 'director._auto', an ImportError was raised:

Traceback (most recent call last):
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/director/_auto.py", line 6, in <module>
    app = create_app()
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/director/__init__.py", line 81, in create_app
    cel_workflows.init_app(app)
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/director/extensions.py", line 32, in init_app
    self.import_user_tasks()
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/director/extensions.py", line 79, in import_user_tasks
    __import__(
  File "/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/pluginbase.py", line 438, in plugin_import
    return self._system_import(import_name, globals, locals,
ModuleNotFoundError: No module named 'pluginbase._internalspace._sp484498cfde69bc7763e699118fdc61f3.tasks.'

**Comment by dppss90008** [comment]
I fixed the error using try and except.

/home/hsieh1216/miniconda3/envs/director/lib/python3.9/site-packages/director/extensions.py

![image](https://user-images.githubusercontent.com/34399929/207754513-962605b6-7ef9-4e58-bbdd-0345a42246ff.png)
