### ISSUE TITLE
add changelog page in documentation

### ISSUE THREAD

**Issue by PaulinCharliquart** [ovh/celery-director#177]
hi,

Can we add the changelog to in the web documentation ?

thanks

**Comment by ncrocfer** [comment]
Hi @PaulinCharliquart ,

We already provide the changelog in 2 places:

- in the [CHANGELOG.txt](https://github.com/ovh/celery-director/blob/master/CHANGELOG.md) file,
- in the list of [Github releases](https://github.com/ovh/celery-director/releases)

Can I ask you what is the objective to also add the changelog in the documentation please? Maybe just adding one line in the doc homepage is enough.

**Comment by PaulinCharliquart** [comment]
hi @ncrocfer,

Just to have everything in one place. I will create a pull request with the changelog link in home page as suggested.

thanks

**Comment by ncrocfer** [comment]
I close this issue as it's not really an issue :)
