### ISSUE TITLE
Better support of newer libraries (Package Dependecy Management)

### ISSUE THREAD

**Issue by frruit** [ovh/celery-director#193]
Hi,
I wanted to test celery-director today within my current project but there is an issue with the installation present.
The alembic version within director is fixed to 1.8.1 but I use 1.9.3. 

```
❯ poetry add celery-director
Using version ^0.9.0 for celery-director

Updating dependencies
Resolving dependencies... (0.5s)

Because no versions of celery-director match >0.9.0,<0.10.0
 and celery-director (0.9.0) depends on alembic (1.8.1), celery-director (>=0.9.0,<0.10.0) requires alembic (1.8.1).
So, because MYPROJECT depends on both alembic (^1.9.3) and celery-director (^0.9.0), version solving failed.
```
It would be great if the requirements.txt would support also newer versions via the **>=** operator.

Thanks a lot!

**Comment by frruit** [comment]
HI @ncrocfer 
and thank you for the replay. I understand the point that  >= is not you preferred way but then use ^ and allow at least updates of minor versions. I would say that at the moment the practise for a framework like director is not reaching enough people which is from my perspective as a user who wants to use it a bad practice :-)
At the moment you can use director only in a project which is created from and where the installation starts with the installation of director. Projects which have celery already in place will for sure use a different dependency tree then you are expecting and with a package manager like poetry your framework is not installable. If you have the goal to reach as many developers as possible you should think about a better specification or establish maybe some CI/CD pipeline with tests which tests your framework with different versions.

So my recommendation is majorly to think if the fixed versions schema is really that what you want.

Kind regards

**Comment by ncrocfer** [comment]
Yes I confirm this is what we want, and we'll not use `^` either. We really prefer to pin our dependencies and have reproductible environments.

For your 2nd point our recommandation is to use [virtual environments](https://docs.python.org/fr/3/library/venv.html) to split your environments, so you will not have requirements conflicts.

> I would say that at the moment the practise for a framework like director is not reaching enough people which is from my perspective as a user who wants to use it a bad practice :-)

Even if Celery Director is not used by a lot of people, we prefer to avoid this kind of problems in the future ^^

BTW I keep this issue opened to upgrade the requirements with newer versions.

**Comment by frruit** [comment]
@ncrocfer thanks for the answer.
I have some questions about the split proposal from you. At the moment i have an already running project with different env. The idea is to run director as a parallel project with it's on env right? How to include then the tasks in my current project to organise them via director?

**Comment by ncrocfer** [comment]
This is up to you, we can't help you on your own project :)
