### ISSUE TITLE
payload modification 

### ISSUE THREAD

**Issue by wqhhust** [ovh/celery-director#195]
Currently the only way to pass parameter from one step to anther is only possible in the case of parent  & child relationship using args, but this is too limited. I will much better if we can even pass parameter from a step to a much deeper/later step (children of children...), this can't be done by simply using args. One possible way is to enable us to modify payload, so that if we want to add a parameter for later step, we just use kwargs["payload"]["new_param_name']="param_value"

**Comment by ncrocfer** [comment]
This feature request is not really linked to Director, but rather to Celery itself no?

Don't forget that Celery Director is just a wrapper on top of Celery.

For information on our side this usecase is fixed by a Redis instance (we store the result from a task then we get it from another one).

**Comment by wqhhust** [comment]
Got it, thx. Let me close it.
