### ISSUE TITLE
question: possible to access app from a task?

### ISSUE THREAD

**Issue by wqhhust** [ovh/celery-director#196]
In the test code, I see lots of place  using app. Is it possible to access app when I define a task using @task(name="some_name")? 

<img width="1048" alt="image" src="https://github.com/ovh/celery-director/assets/5955201/86e603b0-5845-4f71-babf-8c0efbc25b59">

<img width="556" alt="image" src="https://github.com/ovh/celery-director/assets/5955201/e8a618be-b7fd-4918-8ce3-47a3f51a87f6">

**Comment by ncrocfer** [comment]
Can you please explain us the need to access the `app` instance in your tasks code? Some usecases would be appreciated to understand how we can help you.

Your first screenshot displays the tests code, it's normal to access the `app` instance and test its behavior.

**Comment by ncrocfer** [comment]
Closed due to inactivity of the original author.
