### ISSUE TITLE
Could not get Flower to work

### ISSUE THREAD

**Issue by creteurlouis** [ovh/celery-director#32]
Hi,

Thanks for this amazing project , it saves me a lot of time !
I can't get Flower to work  when i click on the button in the console. 
Is it still in development or i am missing something ?

Does   `director webserver`   starts Flower too ?
It might be a nginx configuration issue on my side.

**Comment by maximecaruchet** [comment]
Hello, yes the project is under active development :)
If you want to use flower with director you need to use the following command: `director celery flower`
In fact, if you have initialized a project and want to run it properly you need to run the following commands:
```
director webserver # starts the Web UI and the API
director celery worker # spawns one celery worker to run your tasks
director celery flower # [optional] starts flower to troubleshoot/analyze your tasks
director celery beat # [optional] use if you have periodic tasks in your yaml configuration to run them at the given time period
```

**Comment by creteurlouis** [comment]
It was actually a configuration issue with my nginx.
It works like a charm !

Merci Maxime !
