### ISSUE TITLE
API is not secure

### ISSUE THREAD

**Issue by creteurlouis** [ovh/celery-director#33]
Since  the API is open, it makes the package obsolete for production.
A simple basic auth  using  Flask-HTTPAuth   would solve the problem and allows us to integrate with Lambda Functions

**Comment by ziirish** [comment]
Hello,

You are absolutely right. We are aware of this situation and this point is on our roadmap.

**Comment by ncrocfer** [comment]
It's also important to note that it's possible to use Director behind a reverse proxy adding the authentication layer (it's what we're doing in OVH), so no it's not totally obsolete for production :wink:

However you're totally right, it's not really _user-friendly_ to use a reverse proxy so we need to provide another way to authenticate users. Basic and digest auth can be a first step, but we would like to add other mechanisms like LDAP or OAuth.

We'll come back to you soon with a solution :smiley:
