### ISSUE TITLE
How to use it with Django

### ISSUE THREAD

**Issue by eikebartels** [ovh/celery-director#36]
I would like to use it with Django but I'm not sure how. Do you have any clue to add it as Django app?

**Comment by ziirish** [comment]
Hello,

Sorry, I'm not sure to understand your question.

If you want to launch workflows from your Django application, all you need is to make API calls (HTTP) from your application.
Now if you want to replace the built-in flask server with Django, that's not the way we thought celery-director.

21 mars 2020 11:18:03 PM Eike T. Bartels <notifications@github.com>:

**Comment by baloda** [comment]
@eikebartels 
You have to install and create directory structure as instructed in the doc. you will be able to use in django with easy

**Comment by ncrocfer** [comment]
Thank you for your help @baloda on the Django topic, I can close this issue. Concerning the second point can you create a new issue please ? Indeed it's not yet possible, it will be a new feature :)

**Comment by ncrocfer** [comment]
Sorry @wqhhust but we'll not work to *"integrate Celery Director to Django"*.

Django is one framework among many others, so starting to do that will force us to do the same for all the other frameworks...

If you have a more global need please create a new issue ;)
