### ISSUE TITLE
Frontend JS Error | script.js:26 Uncaught (in promise) TypeError: Cannot read property 'border' of undefined

### ISSUE THREAD

**Issue by mafeko** [ovh/celery-director#39]
Hi team,

first I'd like to thank you for this amazing piece of software enriching the celery-world so much towards simplicity and user-experience!

With the latest version I'm facing some javascript-errors in the frontend after selecting a workflow from the list **(which is in state `progress`)**.

The workflow render-space remains empty until the task fails or succeeds but then it shows the rendering of another  workflow (see status vs. render state)
![image001](https://user-images.githubusercontent.com/6217521/80571150-60fa4600-89fc-11ea-85fe-2dffef9f1676.png)

**Version**
celery==4.4.0
celery-director==0.0.3

In Browser-console:
```javascript
script.js:26 Uncaught (in promise) TypeError: Cannot read property 'border' of undefined
    at getNode (script.js:26)
    at a.refreshNetwork (script.js:92)
    at vuex.min.js:6
    at vuex.min.js:6
    at Array.forEach (<anonymous>)
    at vuex.min.js:6
    at a._withCommit (vuex.min.js:6)
    at a.commit (vuex.min.js:6)
    at commit (vuex.min.js:6)
    at script.js:62
```

tasks.py
```python
from time import sleep
from director import task

@task(bind=False, name="task_a")
def task_a(*args, **kwargs):
    print("task_a")
    sleep(5)

@task(bind=False, name="task_failing")
def task_failing(*args, **kwargs):
    sleep(3)
    print("task_failing")
    raise Exception("Task: failing")

@task(bind=False, name="task_b")
def task_b(*args, **kwargs):
    print("task_b")
    sleep(5.0)
```

workflows.yaml
```yaml
des.COMPLEXFAILING:
  tasks:
    - task_a
    - PARSING:
        type: group
        tasks:
          - task_failing
          - task_b
    - task_a
```

**Comment by mafeko** [comment]
I might have been a bit too fast with this issue. I actually played around with a customized base task `@task(bind=False, name="task_a",base=CustomizedTask)` for the tasks to add some custom logic what happens at `__call__()` and it seems that is causing the issues.

So the frontend could basically be adapted with some more error handling but the root-cause is added in the backend at task-definition level by myself.

Cheers

**Comment by ncrocfer** [comment]
Hi @mafeko,

Thank you for this complete description, I will reproduce it and try to fix the bug ;)

**Comment by ncrocfer** [comment]
The JS error was raised because a bad handling of the `progress` state, I added a new color for it :

![director_progress](https://user-images.githubusercontent.com/1552526/81108818-7948f400-8f19-11ea-83b3-101fcea8dab1.png)

On the other hand I didn't succeeded to reproduce the other problem :

> but then it shows the rendering of another workflow

I think it was a side effect of the JS bug, but if the problem will still be here after the #44 merge I will check again :)

BTW testing this bug showed me that Director is not yet practical for long time running tasks (lot's of f5 to do...). It misses an auto-refresh mode and the permalinks support.
