### ISSUE TITLE
env variable and the variable in settings.py  file does not match

### ISSUE THREAD

**Issue by nanduajith** [ovh/celery-director#58]
In the `director/commands/init.py` file we have used `DIRECTOR_WORKFLOWS_PER_PAGE` as the env variable name. But in the  `settings.py` file's `Config` class we are reading the value from `WORKFLOWS_PER_PAGE` env variable.
```python
self.WORKFLOWS_PER_PAGE = env.int("WORKFLOWS_PER_PAGE", 1000)
```
 We need to make it same.

**Comment by ncrocfer** [comment]
Indeed, thanks for the issue @nanduajith 👍
